### ISSUE TITLE
FATAL  suffixes.flatMap is not a function when running nuxt generate

### ISSUE THREAD

**Issue by Anima-t3d** [nuxt-community/global-components#1]
When I ran `nuxt generate` I got the following error:

```
4:36:19 PM: Verify run directory
4:36:19 PM: Executing user command: npm run generate
4:36:19 PM: > app@1.0.0 generate /opt/build/repo
4:36:19 PM: > nuxt generate
4:36:20 PM:  FATAL  suffixes.flatMap is not a function
4:36:20 PM:   at ModuleContainer.module.exports (node_modules/@nuxtjs/global-components/lib/module.js:16:43)
4:36:20 PM:   at ModuleContainer.addModule (node_modules/@nuxt/core/dist/core.js:190:34)
4:36:20 PM:   at promise.then (node_modules/@nuxt/utils/dist/utils.js:1802:43)
4:36:20 PM:   at process._tickCallback (internal/process/next_tick.js:68:7)
4:36:20 PM:   at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
4:36:20 PM:   at startup (internal/bootstrap/node.js:283:19)
4:36:20 PM:   at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
4:36:20 PM: tput: No value for $TERM and no -T specified
4:36:20 PM:    ╭───────────────────────────────────────────────────╮
4:36:20 PM:    │                                                   │
4:36:20 PM:    │   ✖ Nuxt Fatal Error                              │
4:36:20 PM:    │                                                   │
4:36:20 PM:    │   TypeError: suffixes.flatMap is not a function   │
4:36:20 PM:    │                                                   │
4:36:20 PM:    ╰───────────────────────────────────────────────────╯
4:36:20 PM: npm
4:36:20 PM: ERR! code ELIFECYCLE
4:36:21 PM: failed during stage 'building site': Build script returned non-zero exit code: 1
4:36:20 PM: npm
4:36:20 PM:  ERR! errno
4:36:20 PM:  1
4:36:20 PM: npm ERR! app@1.0.0 generate: `nuxt generate`
```

My machine is running node v10.17
Seems like v11.6 is needed [source](https://thecodebarbarian.com/whats-new-in-es2019-flat-flatmap-catch.html)

**Comment by Anima-t3d** [comment]
Upgrading node via `.nvmrc` > `v12.13.0` worked.
**Note**: Fibers packages does not work on v 11.x on linux...
